In [77]:
#Importamos csv
import pandas as pd

datos = pd.read_csv("acuario.csv")
datos

     Especie   Peso  Long_vert  Long_diag  Long_tras   Altura   Ancho
0          0  242.0       23.2       25.4       30.0  11.5200  4.0200
1          0  290.0       24.0       26.3       31.2  12.4800  4.3056
2          0  340.0       23.9       26.5       31.1  12.3778  4.6961
3          0  363.0       26.3       29.0       33.5  12.7300  4.4555
4          0  430.0       26.5       29.0       34.0  12.4440  5.1340
..       ...    ...        ...        ...        ...      ...     ...
154        4   12.2       11.5       12.2       13.4   2.0904  1.3936
155        4   13.4       11.7       12.4       13.5   2.4300  1.2690
156        4   12.2       12.1       13.0       13.8   2.2770  1.2558
157        4   19.7       13.2       14.3       15.2   2.8728  2.0672
158        4   19.9       13.8       15.0       16.2   2.9322  1.8792

[159 rows x 7 columns]

In [78]:
y = datos["Especie"]
X = datos.drop("Especie", axis=1)
X.head(10)

    Peso  Long_vert  Long_diag  Long_tras   Altura   Ancho
0  242.0       23.2       25.4       30.0  11.5200  4.0200
1  290.0       24.0       26.3       31.2  12.4800  4.3056
2  340.0       23.9       26.5       31.1  12.3778  4.6961
3  363.0       26.3       29.0       33.5  12.7300  4.4555
4  430.0       26.5       29.0       34.0  12.4440  5.1340
5  450.0       26.8       29.7       34.7  13.6024  4.9274
6  500.0       26.8       29.7       34.5  14.1795  5.2785
7  390.0       27.6       30.0       35.0  12.6700  4.6900
8  450.0       27.6       30.0       35.1  14.0049  4.8438
9  500.0       28.5       30.7       36.2  14.2266  4.9594

In [79]:
from sklearn.preprocessing import MinMaxScaler
escalador = MinMaxScaler()

#Escalamos la X
X_escalado = escalador.fit_transform(X)
X_escalado

array([[1.46666667e-01, 3.04854369e-01, 3.09090909e-01, 3.58108108e-01,
        5.68334049e-01, 4.18978349e-01],
       [1.75757576e-01, 3.20388350e-01, 3.25454545e-01, 3.78378378e-01,
        6.24055350e-01, 4.59235453e-01],
       [2.06060606e-01, 3.18446602e-01, 3.29090909e-01, 3.76689189e-01,
        6.18123353e-01, 5.14278868e-01],
       [2.20000000e-01, 3.65048544e-01, 3.74545455e-01, 4.17229730e-01,
        6.38566105e-01, 4.80364795e-01],
       [2.60606061e-01, 3.68932039e-01, 3.74545455e-01, 4.25675676e-01,
        6.21965801e-01, 5.76003608e-01],
       [2.72727273e-01, 3.74757282e-01, 3.87272727e-01, 4.37500000e-01,
        6.89202837e-01, 5.46882048e-01],
       [3.03030303e-01, 3.74757282e-01, 3.87272727e-01, 4.34121622e-01,
        7.22699465e-01, 5.96371786e-01],
       [2.36363636e-01, 3.90291262e-01, 3.92727273e-01, 4.42567568e-01,
        6.35083524e-01, 5.13419035e-01],
       [2.72727273e-01, 3.90291262e-01, 3.92727273e-01, 4.44256757e-01,
        7.12565153e-01, 5.35098106e-01],
       [3.03030303e-01, 4.07766990e-01, 4.05454545e-01, 4.62837838e-01,
        7.25433291e-01, 5.51392648e-01],
       [2.87878788e-01, 4.05825243e-01, 4.10909091e-01, 4.62837838e-01,
        7.27534449e-01, 5.71803112e-01],
       [3.03030303e-01, 4.11650485e-01, 4.10909091e-01, 4.62837838e-01,
        7.33837921e-01, 5.30982183e-01],
       [3.03030303e-01, 4.19417476e-01, 4.20000000e-01, 4.66216216e-01,
        6.98303983e-01, 4.68031123e-01],
       [2.06060606e-01, 4.27184466e-01, 4.29090909e-01, 4.81418919e-01,
        7.07225195e-01, 5.67377086e-01],
       [3.63636364e-01, 4.25242718e-01, 4.29090909e-01, 4.79729730e-01,
        7.67677002e-01, 5.81190798e-01],
       [3.63636364e-01, 4.25242718e-01, 4.29090909e-01, 4.79729730e-01,
        7.95746607e-01, 6.38870095e-01],
       [4.24242424e-01, 4.44660194e-01, 4.47272727e-01, 4.98310811e-01,
        7.62220958e-01, 5.97344384e-01],
       [4.24242424e-01, 4.44660194e-01, 4.47272727e-01, 5.01689189e-01,
        7.66725097e-01, 5.84954330e-01],
       [3.69696970e-01, 4.54368932e-01, 4.56363636e-01, 5.03378378e-01,
        8.07064997e-01, 5.75975417e-01],
       [3.93939394e-01, 4.56310680e-01, 4.56363636e-01, 5.05067568e-01,
        7.39781526e-01, 6.59675237e-01],
       [3.48484848e-01, 4.62135922e-01, 4.65454545e-01, 5.18581081e-01,
        7.77782292e-01, 6.37390054e-01],
       [4.15151515e-01, 4.64077670e-01, 4.65454545e-01, 5.13513514e-01,
        8.27995310e-01, 6.09325665e-01],
       [3.75757576e-01, 4.66019417e-01, 4.74545455e-01, 5.21959459e-01,
        8.00662851e-01, 5.96597316e-01],
       [4.12121212e-01, 4.71844660e-01, 4.83636364e-01, 5.37162162e-01,
        7.97522724e-01, 7.16480604e-01],
       [4.24242424e-01, 4.73786408e-01, 4.83636364e-01, 5.35472973e-01,
        8.42326132e-01, 6.40138701e-01],
       [4.39393939e-01, 4.71844660e-01, 4.83636364e-01, 5.42229730e-01,
        8.49262273e-01, 7.05570591e-01],
       [4.36363636e-01, 4.75728155e-01, 4.83636364e-01, 5.37162162e-01,
        8.49366751e-01, 7.10757781e-01],
       [4.32727273e-01, 4.89320388e-01, 5.01818182e-01, 5.52364865e-01,
        8.58375028e-01, 6.77139716e-01],
       [5.15151515e-01, 4.91262136e-01, 5.01818182e-01, 5.54054054e-01,
        8.80001857e-01, 7.26037438e-01],
       [6.06060606e-01, 5.04854369e-01, 5.20000000e-01, 5.70945946e-01,
        1.00000000e+00, 7.83068336e-01],
       [5.57575758e-01, 5.33980583e-01, 5.47272727e-01, 5.96283784e-01,
        9.46594616e-01, 7.41246617e-01],
       [5.78787879e-01, 5.33980583e-01, 5.47272727e-01, 5.94594595e-01,
        9.49328442e-01, 7.39230943e-01],
       [5.60606061e-01, 5.57281553e-01, 5.65454545e-01, 6.16554054e-01,
        9.88228875e-01, 8.03746617e-01],
       [5.90909091e-01, 5.80582524e-01, 5.92727273e-01, 6.26689189e-01,
        9.81333364e-01, 8.03408322e-01],
       [5.75757576e-01, 5.92233010e-01, 5.92727273e-01, 6.36824324e-01,
        9.22599631e-01, 7.50296008e-01],
       [2.42424242e-02, 1.04854369e-01, 1.03636364e-01, 1.25000000e-01,
        1.40394460e-01, 1.72023004e-01],
       [4.18181818e-02, 1.74757282e-01, 1.78181818e-01, 1.94256757e-01,
        2.07207782e-01, 2.50070478e-01],
       [4.72727273e-02, 1.94174757e-01, 1.89090909e-01, 2.09459459e-01,
        2.23303112e-01, 2.61727560e-01],
       [5.27272727e-02, 2.07766990e-01, 2.07272727e-01, 2.26351351e-01,
        2.25682876e-01, 2.99813938e-01],
       [7.27272727e-02, 2.15533981e-01, 2.10909091e-01, 2.26351351e-01,
        2.60473863e-01, 3.56140054e-01],
       [0.00000000e+00, 2.23300971e-01, 2.20000000e-01, 2.36486486e-01,
        2.75518614e-01, 3.24763194e-01],
       [6.66666667e-02, 2.25242718e-01, 2.25454545e-01, 2.41554054e-01,
        2.57670385e-01, 3.30979364e-01],
       [7.27272727e-02, 2.31067961e-01, 2.29090909e-01, 2.51689189e-01,
        2.54588301e-01, 3.16686401e-01],
       [9.09090909e-02, 2.50485437e-01, 2.47272727e-01, 2.68581081e-01,
        2.36589160e-01, 3.81540370e-01],
       [8.78787879e-02, 2.52427184e-01, 2.47272727e-01, 2.61824324e-01,
        2.84730042e-01, 3.52418809e-01],
       [9.69696970e-02, 2.52427184e-01, 2.56363636e-01, 2.78716216e-01,
        3.07918229e-01, 3.90829387e-01],
       [8.48484848e-02, 2.62135922e-01, 2.56363636e-01, 2.73648649e-01,
        2.79860232e-01, 3.21013757e-01],
       [9.69696970e-02, 2.64077670e-01, 2.56363636e-01, 2.73648649e-01,
        2.71153779e-01, 3.87967975e-01],
       [1.02424242e-01, 2.81553398e-01, 2.83636364e-01, 3.10810811e-01,
        3.36997783e-01, 3.92929635e-01],
       [9.75757576e-02, 2.81553398e-01, 2.72727273e-01, 3.02364865e-01,
        3.01063348e-01, 3.64174560e-01],
       [1.21212121e-01, 2.83495146e-01, 2.74545455e-01, 3.04054054e-01,
        3.29011063e-01, 4.34088859e-01],
       [1.09090909e-01, 3.12621359e-01, 3.05454545e-01, 3.22635135e-01,
        3.11006118e-01, 4.02909337e-01],
       [1.75757576e-01, 3.20388350e-01, 3.20000000e-01, 3.44594595e-01,
        4.14914735e-01, 4.86186288e-01],
       [1.64848485e-01, 3.39805825e-01, 3.38181818e-01, 3.68243243e-01,
        3.96991050e-01, 5.25202977e-01],
       [2.36363636e-01, 4.27184466e-01, 4.23636364e-01, 4.42567568e-01,
        4.50216500e-01, 6.07154939e-01],
       [1.63636364e-01, 3.12621359e-01, 3.20000000e-01, 3.36148649e-01,
        3.86102179e-01, 4.51059991e-01],
       [1.63636364e-01, 3.22330097e-01, 3.29090909e-01, 3.46283784e-01,
        3.72462069e-01, 4.51186852e-01],
       [1.85454545e-01, 3.51456311e-01, 3.56363636e-01, 3.71621622e-01,
        4.09180084e-01, 5.12235002e-01],
       [3.27272727e-01, 4.07766990e-01, 4.10909091e-01, 4.25675676e-01,
        5.23292665e-01, 7.77289129e-01],
       [4.84848485e-01, 5.08737864e-01, 5.09090909e-01, 5.20270270e-01,
        5.82334026e-01, 7.78924222e-01],
       [6.06060606e-01, 5.78640777e-01, 5.74545455e-01, 5.86148649e-01,
        6.16741929e-01, 7.72073748e-01],
       [3.33333333e-02, 1.16504854e-01, 1.14545455e-01, 1.30067568e-01,
        2.97128031e-01, 1.80268945e-01],
       [3.63636364e-02, 1.32038835e-01, 1.29090909e-01, 1.45270270e-01,
        2.81439003e-01, 1.78535183e-01],
       [5.45454545e-02, 1.70873786e-01, 1.69090909e-01, 1.85810811e-01,
        3.29498624e-01, 2.29110284e-01],
       [7.27272727e-02, 1.94174757e-01, 1.92727273e-01, 2.11148649e-01,
        3.86787087e-01, 2.63658660e-01],
       [9.09090909e-02, 2.11650485e-01, 2.10909091e-01, 2.29729730e-01,
        4.15843423e-01, 3.16474966e-01],
       [8.48484848e-02, 2.23300971e-01, 2.23636364e-01, 2.43243243e-01,
        3.95226542e-01, 3.16700496e-01],
       [1.03030303e-01, 2.23300971e-01, 2.23636364e-01, 2.43243243e-01,
        4.45050672e-01, 3.33051421e-01],
       [8.78787879e-02, 2.38834951e-01, 2.38181818e-01, 2.58445946e-01,
        4.64808516e-01, 2.97347203e-01],
       [1.21212121e-01, 2.66019417e-01, 2.65454545e-01, 2.87162162e-01,
        5.00179933e-01, 3.68741543e-01],
       [1.65454545e-01, 3.00970874e-01, 3.01818182e-01, 3.24324324e-01,
        5.43259464e-01, 4.36456924e-01],
       [1.81818182e-01, 3.20388350e-01, 3.20000000e-01, 3.41216216e-01,
        5.59511510e-01, 4.49142986e-01],
       [3.57575758e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.22653030e-02, 5.08006315e-02],
       [1.93939394e-02, 9.70873786e-02, 9.63636364e-02, 9.96621622e-02,
        1.04454221e-01, 1.34133965e-01],
       [2.42424242e-02, 1.22330097e-01, 1.20000000e-01, 1.21621622e-01,
        1.21634956e-01, 1.95139829e-01],
       [3.12121212e-02, 1.45631068e-01, 1.41818182e-01, 1.41891892e-01,
        1.66235214e-01, 2.23274696e-01],
       [4.24242424e-02, 1.59223301e-01, 1.63636364e-01, 1.63851351e-01,
        1.65979824e-01, 2.66957037e-01],
       [6.06060606e-02, 1.68932039e-01, 1.74545455e-01, 1.75675676e-01,
        2.02802317e-01, 3.20534506e-01],
       [4.72727273e-02, 1.80582524e-01, 1.87272727e-01, 1.79054054e-01,
        2.01455719e-01, 2.92596978e-01],
       [4.84848485e-02, 1.88349515e-01, 1.92727273e-01, 1.92567568e-01,
        2.26797302e-01, 2.82278981e-01],
       [5.15151515e-02, 2.00000000e-01, 2.03636364e-01, 2.02702703e-01,
        1.97880269e-01, 2.80390167e-01],
       [5.15151515e-02, 2.07766990e-01, 2.10909091e-01, 2.06081081e-01,
        1.94653077e-01, 2.43064953e-01],
       [6.66666667e-02, 2.23300971e-01, 2.29090909e-01, 2.31418919e-01,
        2.30088341e-01, 3.53433694e-01],
       [6.96969697e-02, 2.23300971e-01, 2.29090909e-01, 2.31418919e-01,
        2.43148021e-01, 3.18547023e-01],
       [7.57575758e-02, 2.23300971e-01, 2.29090909e-01, 2.31418919e-01,
        2.30088341e-01, 3.69291272e-01],
       [7.87878788e-02, 2.29126214e-01, 2.34545455e-01, 2.36486486e-01,
        2.70225091e-01, 3.50473613e-01],
       [7.27272727e-02, 2.42718447e-01, 2.47272727e-01, 2.48310811e-01,
        2.54321303e-01, 3.32642648e-01],
       [7.27272727e-02, 2.42718447e-01, 2.47272727e-01, 2.48310811e-01,
        2.27041083e-01, 3.49205007e-01],
       [7.87878788e-02, 2.42718447e-01, 2.47272727e-01, 2.48310811e-01,
        2.54321303e-01, 3.49205007e-01],
       [8.18181818e-02, 2.42718447e-01, 2.47272727e-01, 2.48310811e-01,
        2.40681193e-01, 3.49205007e-01],
       [6.66666667e-02, 2.42718447e-01, 2.47272727e-01, 2.48310811e-01,
        2.20221028e-01, 4.15454443e-01],
       [7.87878788e-02, 2.52427184e-01, 2.56363636e-01, 2.56756757e-01,
        2.39578375e-01, 3.63159675e-01],
       [9.09090909e-02, 2.52427184e-01, 2.56363636e-01, 2.56756757e-01,
        2.93906644e-01, 3.63159675e-01],
       [8.78787879e-02, 2.56310680e-01, 2.60000000e-01, 2.60135135e-01,
        2.45220157e-01, 3.64005413e-01],
       [9.09090909e-02, 2.62135922e-01, 2.65454545e-01, 2.65202703e-01,
        2.02575949e-01, 3.63441588e-01],
       [1.03030303e-01, 2.71844660e-01, 2.74545455e-01, 2.73648649e-01,
        2.63898401e-01, 3.77396256e-01],
       [1.36363636e-01, 2.81553398e-01, 2.83636364e-01, 2.82094595e-01,
        3.22986197e-01, 3.77114344e-01],
       [8.78787879e-02, 2.81553398e-01, 2.83636364e-01, 2.82094595e-01,
        2.69702704e-01, 3.91491881e-01],
       [1.13939394e-01, 2.93203883e-01, 2.94545455e-01, 2.93918919e-01,
        2.90505323e-01, 4.39529770e-01],
       [1.09090909e-01, 3.00970874e-01, 3.01818182e-01, 2.98986486e-01,
        2.73446479e-01, 3.71546572e-01],
       [1.19393939e-01, 3.10679612e-01, 3.12727273e-01, 3.07432432e-01,
        2.80498706e-01, 4.49847767e-01],
       [1.32121212e-01, 3.39805825e-01, 3.29090909e-01, 3.24324324e-01,
        3.15730820e-01, 4.36456924e-01],
       [1.81818182e-01, 3.43689320e-01, 3.43636364e-01, 3.36148649e-01,
        3.82770510e-01, 5.76468764e-01],
       [1.57575758e-01, 3.47572816e-01, 3.47272727e-01, 3.39527027e-01,
        3.15684385e-01, 4.63379567e-01],
       [1.60606061e-01, 3.47572816e-01, 3.47272727e-01, 3.39527027e-01,
        3.08974612e-01, 4.63379567e-01],
       [1.51515152e-01, 3.47572816e-01, 3.47272727e-01, 3.39527027e-01,
        3.22394159e-01, 4.95968651e-01],
       [1.51515152e-01, 3.57281553e-01, 3.56363636e-01, 3.47972973e-01,
        3.53598087e-01, 4.44942490e-01],
       [1.81818182e-01, 3.76699029e-01, 3.69090909e-01, 3.59797297e-01,
        3.39946368e-01, 5.05722824e-01],
       [1.93939394e-01, 3.94174757e-01, 3.92727273e-01, 3.85135135e-01,
        3.41710876e-01, 5.24921065e-01],
       [3.11515152e-01, 4.46601942e-01, 4.43636364e-01, 4.25675676e-01,
        4.81849947e-01, 7.00608931e-01],
       [3.36969697e-01, 4.75728155e-01, 4.74545455e-01, 4.67905405e-01,
        4.94996692e-01, 7.52692264e-01],
       [5.09090909e-01, 4.85436893e-01, 4.83636364e-01, 4.81418919e-01,
        5.66499890e-01, 9.51186852e-01],
       [4.15151515e-01, 5.14563107e-01, 5.10909091e-01, 5.10135135e-01,
        5.31244558e-01, 8.19857916e-01],
       [4.24242424e-01, 5.14563107e-01, 5.01818182e-01, 4.98310811e-01,
        5.15462661e-01, 8.02492106e-01],
       [4.24242424e-01, 5.24271845e-01, 5.20000000e-01, 5.16891892e-01,
        5.28574579e-01, 7.35368742e-01],
       [4.18181818e-01, 5.26213592e-01, 5.20000000e-01, 5.15202703e-01,
        5.13291852e-01, 7.49746279e-01],
       [5.45454545e-01, 5.63106796e-01, 5.56363636e-01, 5.50675676e-01,
        5.46080355e-01, 9.08575778e-01],
       [3.93939394e-01, 5.63106796e-01, 5.56363636e-01, 5.50675676e-01,
        5.46080355e-01, 6.98494587e-01],
       [4.96969697e-01, 5.65048544e-01, 5.56363636e-01, 5.48986486e-01,
        6.21228655e-01, 8.88559991e-01],
       [5.15151515e-01, 5.70873786e-01, 5.74545455e-01, 5.65878378e-01,
        5.92050428e-01, 8.54025710e-01],
       [5.45454545e-01, 5.72815534e-01, 5.74545455e-01, 5.69256757e-01,
        5.80523084e-01, 8.70743121e-01],
       [6.15151515e-01, 5.72815534e-01, 5.74545455e-01, 5.67567568e-01,
        6.18297482e-01, 9.04206134e-01],
       [4.96969697e-01, 5.74757282e-01, 5.74545455e-01, 5.69256757e-01,
        5.45987486e-01, 7.86874154e-01],
       [6.66666667e-01, 6.11650485e-01, 6.10909091e-01, 6.04729730e-01,
        6.42640725e-01, 8.20478124e-01],
       [6.06060606e-01, 6.27184466e-01, 6.29090909e-01, 6.14864865e-01,
        5.92294208e-01, 8.78101037e-01],
       [6.66666667e-01, 6.33009709e-01, 6.29090909e-01, 6.19932432e-01,
        6.25941748e-01, 8.97736243e-01],
       [6.06060606e-01, 6.34951456e-01, 6.38181818e-01, 6.28378378e-01,
        6.31252684e-01, 1.00000000e+00],
       [6.06060606e-01, 6.52427184e-01, 6.47272727e-01, 6.38513514e-01,
        6.24566128e-01, 9.23009698e-01],
       [1.21212121e-01, 4.36893204e-01, 4.34545455e-01, 4.39189189e-01,
        2.22861985e-01, 3.28146143e-01],
       [1.81818182e-01, 4.69902913e-01, 4.65454545e-01, 4.89864865e-01,
        2.30976400e-01, 4.38430311e-01],
       [1.81818182e-01, 4.89320388e-01, 4.83636364e-01, 5.06756757e-01,
        2.44245034e-01, 4.70342806e-01],
       [1.81818182e-01, 5.30097087e-01, 5.25454545e-01, 5.23648649e-01,
        2.64676178e-01, 4.18950158e-01],
       [2.60606061e-01, 5.43689320e-01, 5.38181818e-01, 5.35472973e-01,
        3.22812068e-01, 4.97420501e-01],
       [2.09090909e-01, 5.53398058e-01, 5.47272727e-01, 5.43918919e-01,
        2.70921607e-01, 4.12917230e-01],
       [2.76363636e-01, 6.31067961e-01, 6.20000000e-01, 6.19932432e-01,
        3.22231638e-01, 4.61617614e-01],
       [3.09090909e-01, 6.31067961e-01, 6.20000000e-01, 6.19932432e-01,
        2.95822063e-01, 4.80858142e-01],
       [3.27272727e-01, 6.33009709e-01, 6.29090909e-01, 6.25000000e-01,
        3.51601407e-01, 5.75383401e-01],
       [3.03030303e-01, 6.69902913e-01, 6.65454545e-01, 6.62162162e-01,
        3.03657871e-01, 5.42456022e-01],
       [3.43636364e-01, 6.93203883e-01, 6.83636364e-01, 6.73986486e-01,
        3.51949665e-01, 5.38791159e-01],
       [4.66666667e-01, 7.24271845e-01, 7.20000000e-01, 7.16216216e-01,
        3.45448847e-01, 6.10115020e-01],
       [5.75757576e-01, 7.92233010e-01, 7.87272727e-01, 7.82094595e-01,
        4.17782060e-01, 7.22203428e-01],
       [7.57575758e-01, 8.64077670e-01, 8.65454545e-01, 8.59797297e-01,
        5.19943582e-01, 8.36899526e-01],
       [9.69696970e-01, 9.41747573e-01, 9.38181818e-01, 9.32432432e-01,
        4.56891448e-01, 7.18369418e-01],
       [9.39393939e-01, 9.41747573e-01, 9.38181818e-01, 9.32432432e-01,
        4.56891448e-01, 7.18369418e-01],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        5.27239590e-01, 9.06686964e-01],
       [4.06060606e-03, 3.49514563e-02, 2.54545455e-02, 3.37837838e-02,
        6.03647423e-04, 0.00000000e+00],
       [4.54545455e-03, 4.85436893e-02, 3.81818182e-02, 4.72972973e-02,
        1.41392800e-02, 1.58434822e-02],
       [4.24242424e-03, 5.04854369e-02, 4.00000000e-02, 4.72972973e-02,
        0.00000000e+00, 1.42083897e-02],
       [5.87878788e-03, 5.63106796e-02, 4.72727273e-02, 5.40540541e-02,
        2.71409168e-02, 4.68538566e-02],
       [5.93939394e-03, 6.21359223e-02, 5.09090909e-02, 6.08108108e-02,
        2.05936640e-02, 3.23635544e-02],
       [5.27272727e-03, 6.40776699e-02, 5.27272727e-02, 6.41891892e-02,
        1.44991468e-02, 3.34912043e-02],
       [6.06060606e-03, 7.37864078e-02, 6.18181818e-02, 7.26351351e-02,
        2.81798869e-02, 3.32938656e-02],
       [6.00000000e-03, 7.37864078e-02, 6.18181818e-02, 7.26351351e-02,
        2.81798869e-02, 1.66751240e-02],
       [5.93939394e-03, 7.57281553e-02, 6.54545455e-02, 7.43243243e-02,
        2.76284782e-02, 1.42083897e-02],
       [7.39393939e-03, 7.76699029e-02, 6.90909091e-02, 7.77027027e-02,
        2.10115738e-02, 4.87708615e-02],
       [8.12121212e-03, 8.15533981e-02, 7.27272727e-02, 7.93918919e-02,
        4.07229839e-02, 3.12077131e-02],
       [7.39393939e-03, 8.93203883e-02, 8.36363636e-02, 8.44594595e-02,
        3.18424016e-02, 2.93470907e-02],
       [1.19393939e-02, 1.10679612e-01, 1.07272727e-01, 1.08108108e-01,
        6.64244338e-02, 1.43718990e-01],
       [1.20606061e-02, 1.22330097e-01, 1.20000000e-01, 1.25000000e-01,
        6.98721893e-02, 1.17219215e-01]])

In [80]:
#Codificamos la y
from tensorflow.keras.utils import to_categorical
y_codificado = to_categorical(y)

In [81]:
#Hacemos el split
from sklearn.model_selection import train_test_split
X_train_escalado, X_test_escalado, y_train_cod,  y_test_cod = train_test_split(X_escalado, y_codificado, stratify=y_codificado)

In [82]:
X_train_escalado.shape
y_codificado[0]

array([1., 0., 0., 0., 0., 0., 0.])

In [83]:
#Montar red
from keras.models import Sequential
from keras.layers import Dense

red = Sequential()
red.add(Dense(15, activation="sigmoid", input_shape=(6,)))
red.add(Dense(7, activation="softmax"))

c:\Users\David\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [84]:
red.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 15)             │           105 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 7)              │           112 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 217 (868.00 B)

 Trainable params: 217 (868.00 B)

 Non-trainable params: 0 (0.00 B)

In [85]:
from keras.optimizers import Adam
red.compile(
    loss="categorical_crossentropy",
    metrics = ["accuracy"],
    optimizer = "adam"
)

In [86]:
print(len(X_train_escalado))
print(len(X_test_escalado))
print(len(y_train_cod))
print(len(y_test_cod))

119
40
119
40

In [87]:
red.fit(
    X_train_escalado, y_train_cod,
    epochs=500,
    batch_size=1,
    verbose=False,
    validation_data=(X_test_escalado,y_test_cod)
)

In [88]:
red.evaluate(X_test_escalado, y_test_cod)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8000 - loss: 0.4416

[0.44164448976516724, 0.800000011920929]